[package]
name = "rada"
version = "0.1.0"
edition = "2018"

[dependencies]
rust-htslib = "0.36.0"
fstrings = "0.2.3"
rayon = "1.5.1"
scoped-tls-hkt = "0.1"
bio-types = "0.12.0"
flate2 = "1.0.20"
bio = "0.34.0"
itertools = "0.10.1"
derive_more = "0.99.16"
clap = { version = "3.0.0-beta.2", features = ["wrap_help"]}

[dev-dependencies]
mockall = "0.10.2"

[profile.release]
lto = true
