[package]
name = "rada"
version = "0.0.1"
edition = "2018"

[dependencies]
rust-htslib = "0.36.0"
fstrings = "0.2.3"
rayon = "1.5.1"
thread_local = "1.1.3"
bio-types = "0.12.0"
flate2 = "1.0.20"
bio = "0.34.0"
itertools = "0.10.1"
clap = { git = "https://github.com/clap-rs/clap", rev = "5a1a209", features = ["wrap_help"] }
indicatif = { version = "0.16.2", features = ["rayon"] }
derive-getters = "0.2.0"
derive_more = "0.99.16"

[dev-dependencies]
mockall = "0.10.2"

[profile.release]
lto = true
